目標詳細メニュー実装
camp-team/okr-app pull request #126
Opened 2020-08-13 11:44 UTC by peyo-code

fix #54 

目標詳細メニューを実装しました。

- [x] MatMenuModuleのimport
- [x] mat-icon追加
- [x] menu実装
- [x] menuボタンレイアウト

![目標詳細メニュー](https://user-images.githubusercontent.com/61979156/90130513-8e99ae00-dda5-11ea-975d-675ad8b0b2d8.gif)

ご確認よろしくお願い致します。

2020-08-17 02:38 UTC, dninomiya requested changes

2020-08-17 02:38 UTC, deerboy commented on src/app/home-detail/home-detail.component.html
> +  </p>
同じ要素が繰り替えし登場してる（primary2, 3）のでループで表現しましょう

2020-08-26 13:29 UTC, peyo-code commented
ありがとうございます。
連絡が遅くなってしまい、申し訳ございません。
cloud firestoreからフィールドのデータ(primary)を取得し、取得したデータの数分を画面に表示したいのですが、その際にどのように記載していけば良いのか教えて頂きたいです。

現状、ループで表現ができているのですが、[home-detail.component.ts](https://github.com/camp-team/okr-app/blob/13af733d93c426bec789c1bdc0e9f00f5e363ef4/src/app/home-detail/home-detail.component.ts)にてgetTimes()で指定している数字分が画面上に表示されてしまいます。
こちらを指定した数分ではなく取得したデータ分画面に表示したいと考えております。
下記該当コードになります。

ご確認よろしくお願い致します🙇‍♂️

[home-detail.component.html](https://github.com/camp-team/okr-app/blob/13af733d93c426bec789c1bdc0e9f00f5e363ef4/src/app/home-detail/home-detail.component.html)
[home-detail.component.ts](https://github.com/camp-team/okr-app/blob/13af733d93c426bec789c1bdc0e9f00f5e363ef4/src/app/home-detail/home-detail.component.ts)

2020-08-26 23:57 UTC, deerboy approved these changes
元々この時点ではダミーデータを意図していたと思うので、ループ化OKということでマージします。実際のデータを取得してループで流す方法はドキュメント参照してみてください。

https://to.camp/lesson?v=4JGWSlOdncsjjoRpkxLQ#%E3%82%B3%E3%83%AC%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E5%8F%96%E5%BE%97

2020-08-26 23:57 UTC, merged

2020-08-27 11:22 UTC, peyo-code commented
かしこまりました。
ありがとうございます